export const GET_CARINFO_REQUEST = 'GET_CARINFO_REQUEST';
export const GET_CARINFO_SUCCESS = 'GET_CARINFO_SUCCESS'
export const GET_CARINFO_FAIL = 'GET_CARINFO_FAIL'
export const GET_COLLECTS_REQUEST = 'GET_COLLECTS_REQUEST';
export const GET_COLLECTS_SUCCESS = 'GET_COLLECTS_SUCCESS'
export const GET_COLLECTS_FAIL = 'GET_COLLECTS_FAIL'
export const ADD_COLLECT_REQUEST = 'ADD_COLLECT_REQUEST';
export const ADD_COLLECT_SUCCESS = 'GET_COLLECT_SUCCESS'
export const ADD_COLLECT_FAIL = 'ADD_COLLECT_FAIL'

export const GET_COLLECTSBYID_REQUEST = 'GET_COLLECTSBYID_REQUEST';
export const GET_COLLECTSBYID_SUCCESS = 'GET_COLLECTSBYID_SUCCESS'
export const GET_COLLECTSBYID_FAIL = 'GET_COLLECTSBYID_FAIL'

export const GET_CHECKDATA_REQUEST = 'GET_CHECKDATA_REQUEST';
export const GET_CHECKDATA_SUCCESS = 'GET_CHECKDATA_SUCCESS'
export const GET_CHECKDATA_FAIL = 'GET_CHECKDATA_FAIL'

export const GET_CARSINFO_SUCCESS = 'GET_CARSINFO_SUCCESS'